# Generated by Django 3.0.6 on 2020-05-12 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aboutme', '0002_auto_20200512_2358'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='project_desctiption',
            new_name='project_description',
        ),
    ]
