# Generated by Django 3.0.6 on 2020-05-12 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aboutme', '0005_me'),
    ]

    operations = [
        migrations.AddField(
            model_name='me',
            name='about_me_brief',
            field=models.CharField(default='tech geek', max_length=100),
            preserve_default=False,
        ),
    ]
