# Generated by Django 3.0.6 on 2020-05-12 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aboutme', '0008_auto_20200513_0133'),
    ]

    operations = [
        migrations.AddField(
            model_name='me',
            name='image_front',
            field=models.ImageField(default=0, upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='me',
            name='image_main',
            field=models.ImageField(default=90, upload_to=''),
            preserve_default=False,
        ),
    ]
