# Generated by Django 3.0.6 on 2020-05-12 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aboutme', '0009_auto_20200513_0250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='me',
            name='image_front',
            field=models.ImageField(upload_to='myImages'),
        ),
        migrations.AlterField(
            model_name='me',
            name='image_main',
            field=models.ImageField(upload_to='myImages'),
        ),
    ]
