# Generated by Django 3.0.6 on 2020-05-12 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aboutme', '0011_auto_20200513_0320'),
    ]

    operations = [
        migrations.RenameField(
            model_name='me',
            old_name='image_front',
            new_name='image',
        ),
        migrations.RemoveField(
            model_name='me',
            name='image_main',
        ),
    ]
