# Generated by Django 3.0.6 on 2020-05-12 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aboutme', '0012_auto_20200513_0337'),
    ]

    operations = [
        migrations.AddField(
            model_name='me',
            name='cv',
            field=models.FileField(blank=True, null=True, upload_to='myFiles'),
        ),
        migrations.AddField(
            model_name='me',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='myFiles'),
        ),
    ]
