# Generated by Django 3.0.6 on 2020-05-14 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aboutme', '0013_auto_20200513_0345'),
    ]

    operations = [
        migrations.AddField(
            model_name='me',
            name='link_facebook',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='me',
            name='link_github',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='me',
            name='link_instagram',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='me',
            name='link_linkedin',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='me',
            name='link_twitter',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
