# Generated by Django 3.0.6 on 2020-05-14 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aboutme', '0015_auto_20200514_1749'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='skill_category',
            field=models.CharField(choices=[('Programming Language', 'Programming Language'), ('Tools & Technologies', 'Tools & Technologies'), ('Other Skills', 'OtherSkills')], default='Other Skills', max_length=20),
        ),
    ]
