# Generated by Django 3.0.6 on 2020-05-14 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aboutme', '0016_skill_skill_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exp_title', models.CharField(max_length=80)),
                ('exp_description', models.TextField()),
                ('exp_priority', models.IntegerField()),
                ('completed', models.BooleanField()),
                ('start_date', models.DateTimeField(verbose_name='start date')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='end date')),
            ],
        ),
        migrations.DeleteModel(
            name='Job',
        ),
        migrations.AlterField(
            model_name='skill',
            name='skill_category',
            field=models.CharField(choices=[('Programming Language', 'Programming Language'), ('Tools & Technologies', 'Tools & Technologies'), ('Other Skills', 'Other Skills')], default='Other Skills', max_length=20),
        ),
    ]
