# Generated by Django 3.0.6 on 2020-05-14 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aboutme', '0017_auto_20200515_0028'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_title', models.CharField(max_length=100)),
                ('certificate_priority', models.IntegerField(default=0)),
                ('certificate_issuer', models.CharField(max_length=80)),
                ('certificate_credential_id', models.CharField(max_length=100)),
                ('certificate_credential_url', models.CharField(max_length=150)),
                ('issue_date', models.DateTimeField(verbose_name='Issue date')),
                ('expires', models.BooleanField()),
                ('expiration_date', models.DateTimeField(blank=True, null=True, verbose_name='Expiration Date')),
            ],
        ),
        migrations.AlterField(
            model_name='experience',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='End date'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='start_date',
            field=models.DateTimeField(verbose_name='Start date'),
        ),
    ]
